# Generated by Django 4.1.5 on 2023-01-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('garages', models.IntegerField()),
                ('type', models.IntegerField(blank=True, choices=[(1, 'For Rent'), (2, 'For Sale'), (3, 'For House')], null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Longitude', models.FloatField(blank=True, max_length=200, null=True)),
                ('Lattitude', models.FloatField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userauth.timestampmodel')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_main', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='userauth.advertisementsite')),
            ],
            bases=('userauth.timestampmodel',),
        ),
        migrations.DeleteModel(
            name='SiteProperty',
        ),
    ]
